// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obstacles.proto

package obstacles;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:obstacles.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string streets = 1;</code>
   */
  java.lang.String getStreets();
  /**
   * <code>string streets = 1;</code>
   */
  com.google.protobuf.ByteString
      getStreetsBytes();
}
