// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ObstaclesService.proto

package Obstacles;

public final class ObstaclesServiceImpl {
  private ObstaclesServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Obstacles_StringMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Obstacles_StringMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ObstaclesService.proto\022\tObstacles\"\037\n\rS" +
      "tringMessage\022\016\n\006pointA\030\001 \001(\t2P\n\tObstacle" +
      "s\022C\n\tObstacles\022\030.Obstacles.StringMessage" +
      "\032\030.Obstacles.StringMessage\"\0000\001B#\n\tObstac" +
      "lesB\024ObstaclesServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Obstacles_StringMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Obstacles_StringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Obstacles_StringMessage_descriptor,
        new java.lang.String[] { "PointA", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
