// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obstacles.proto

package obstacles;

public final class obstaclesServiceImpl {
  private obstaclesServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obstacles_StringMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obstacles_StringMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017obstacles.proto\022\tobstacles\"\035\n\rStringMe" +
      "ssage\022\014\n\004city\030\001 \001(\t2R\n\tobstacles\022E\n\tObst" +
      "acles\022\030.obstacles.StringMessage\032\030.obstac" +
      "les.StringMessage\"\000(\0010\001B#\n\tobstaclesB\024ob" +
      "staclesServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_obstacles_StringMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_obstacles_StringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obstacles_StringMessage_descriptor,
        new java.lang.String[] { "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
