// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obstacles.proto

package obstacles;

public final class obstaclesServiceImpl {
  private obstaclesServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obstacles_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obstacles_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017obstacles.proto\022\tobstacles\"\032\n\007Message\022" +
      "\017\n\007streets\030\001 \001(\t2L\n\tobstacles\022?\n\017Obstacl" +
      "esInRoad\022\022.obstacles.Message\032\022.obstacles" +
      ".Message\"\000(\0010\001B#\n\tobstaclesB\024obstaclesSe" +
      "rviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_obstacles_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_obstacles_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obstacles_Message_descriptor,
        new java.lang.String[] { "Streets", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
