// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ObstaclesService.proto

package Obstacles;

public interface StringMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Obstacles.StringMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pointA = 1;</code>
   */
  java.lang.String getPointA();
  /**
   * <code>string pointA = 1;</code>
   */
  com.google.protobuf.ByteString
      getPointABytes();
}
