// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obstacles.proto

package obstacles;

public interface StringMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:obstacles.StringMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string street = 1;</code>
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 1;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();
}
