// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cityInSystemService.proto

package cityInService;

public final class cityInServiceImpl {
  private cityInServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cityInService_StringMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cityInService_StringMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031cityInSystemService.proto\022\rcityInServi" +
      "ce\"\035\n\rStringMessage\022\014\n\004city\030\001 \001(\t2^\n\rcit" +
      "yInService\022M\n\rCityInService\022\034.cityInServ" +
      "ice.StringMessage\032\034.cityInService.String" +
      "Message\"\000B$\n\rcityInServiceB\021cityInServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cityInService_StringMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cityInService_StringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cityInService_StringMessage_descriptor,
        new java.lang.String[] { "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
