// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cityInSystemService.proto

package cityInService;

public interface IntMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cityInService.IntMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 2;</code>
   */
  int getTemperature();
}
