// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrentTrafficService.proto

package CurrentTraffic;

public final class CurrentTrafficServiceImpl {
  private CurrentTrafficServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrentTraffic_StringMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrentTraffic_StringMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CurrentTrafficService.proto\022\016CurrentTr" +
      "affic\"\037\n\rStringMessage\022\016\n\006points\030\001 \001(\t2k" +
      "\n\016CurrentTraffic\022Y\n\025currentTrafficServic" +
      "e\022\035.CurrentTraffic.StringMessage\032\035.Curre" +
      "ntTraffic.StringMessage\"\000(\001B-\n\016CurrentTr" +
      "afficB\031CurrentTrafficServiceImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CurrentTraffic_StringMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CurrentTraffic_StringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrentTraffic_StringMessage_descriptor,
        new java.lang.String[] { "Points", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
