// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currentTraffic.proto

package currentTraffic;

public final class currentTrafficServiceImpl {
  private currentTrafficServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_currentTraffic_StringMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_currentTraffic_StringMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024currentTraffic.proto\022\016currentTraffic\"\035" +
      "\n\rStringMessage\022\014\n\004city\030\001 \001(\t2\267\001\n\016curren" +
      "tTraffic\022R\n\016CurrentTraffic\022\035.currentTraf" +
      "fic.StringMessage\032\035.currentTraffic.Strin" +
      "gMessage\"\0000\001\022Q\n\rTrafficInCity\022\035.currentT" +
      "raffic.StringMessage\032\035.currentTraffic.St" +
      "ringMessage\"\000(\001B-\n\016currentTrafficB\031curre" +
      "ntTrafficServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_currentTraffic_StringMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_currentTraffic_StringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_currentTraffic_StringMessage_descriptor,
        new java.lang.String[] { "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
