// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currentTraffic.proto

package currentTraffic;

public interface DatesTrafficOrBuilder extends
    // @@protoc_insertion_point(interface_extends:currentTraffic.DatesTraffic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 date = 1;</code>
   */
  int getDate();
}
