// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrentTrafficService.proto

package CurrentTraffic;

public interface StringMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurrentTraffic.StringMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string points = 1;</code>
   */
  java.lang.String getPoints();
  /**
   * <code>string points = 1;</code>
   */
  com.google.protobuf.ByteString
      getPointsBytes();
}
