// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currentTraffic.proto

package currentTraffic;

public interface StringMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:currentTraffic.StringM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city1 = 1;</code>
   */
  java.lang.String getCity1();
  /**
   * <code>string city1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getCity1Bytes();
}
